import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Student, SchoolSettings, Grade } from './supabase';

export const generateReportCard = async (student: Student, settings: SchoolSettings) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Header
  doc.setFillColor(240, 240, 240);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  if (settings.logo) {
    try {
      doc.addImage(settings.logo, 'PNG', 14, 10, 20, 20);
    } catch (e) {
      console.warn('Could not add logo to PDF:', e);
    }
  }

  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  doc.text(settings.name || 'School Report Card', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.text(`Academic Year: ${settings.academic_year || 'N/A'}`, pageWidth / 2, 30, { align: 'center' });

  // Student Info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Student Name: ${student.name}`, 14, 55);
  doc.text(`Student ID: ${student.studentId}`, 14, 62);
  doc.text(`Class: ${student.class}`, 14, 69);
  
  doc.text(`Attendance: ${student.attendance}%`, pageWidth - 60, 55);
  doc.text(`Fee Status: ${student.feeStatus}`, pageWidth - 60, 62);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 60, 69);

  // Grades Table
  const grades = student.grades && student.grades.length > 0 ? student.grades : [
    { subject: 'Mathematics', score: 85, total: 100, term: 'Final', date: '' },
    { subject: 'Science', score: 78, total: 100, term: 'Final', date: '' },
    { subject: 'English', score: 92, total: 100, term: 'Final', date: '' },
    { subject: 'History', score: 88, total: 100, term: 'Final', date: '' },
    { subject: 'Geography', score: 81, total: 100, term: 'Final', date: '' },
  ] as Grade[];

  const tableData = grades.map(g => [
    g.subject,
    g.term,
    g.score.toString(),
    g.total.toString(),
    `${((g.score / g.total) * 100).toFixed(1)}%`
  ]);

  autoTable(doc, {
    startY: 80,
    head: [['Subject', 'Term', 'Score', 'Total', 'Percentage']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [51, 122, 183], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
  });

  // Summary
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const totalScore = grades.reduce((sum, g) => sum + g.score, 0);
  const totalPossible = grades.reduce((sum, g) => sum + g.total, 0);
  const overallPercentage = ((totalScore / totalPossible) * 100).toFixed(1);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Overall Percentage: ${overallPercentage}%`, 14, finalY + 10);
  
  let grade = 'F';
  const p = parseFloat(overallPercentage);
  if (p >= 90) grade = 'A+';
  else if (p >= 80) grade = 'A';
  else if (p >= 70) grade = 'B';
  else if (p >= 60) grade = 'C';
  else if (p >= 50) grade = 'D';
  
  doc.text(`Final Grade: ${grade}`, 14, finalY + 20);

  // Footer
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by EduAssist', pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });

  doc.save(`${student.name}_Report_Card.pdf`);
};

export const generateFeeReceipt = async (student: Student, settings: SchoolSettings) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Header
  doc.setFillColor(51, 122, 183);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  if (settings.logo) {
    try {
      doc.addImage(settings.logo, 'PNG', 14, 10, 20, 20);
    } catch (e) {
      console.warn('Could not add logo to PDF:', e);
    }
  }

  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text('FEE RECEIPT', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(settings.name || 'School Name', pageWidth / 2, 30, { align: 'center' });

  // Receipt Details
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`Receipt No: REC-${Date.now().toString().slice(-6)}`, 14, 50);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 50, 50);

  // Student Info
  doc.setFontSize(12);
  doc.text('Student Details:', 14, 65);
  doc.setFontSize(10);
  doc.text(`Name: ${student.name}`, 14, 72);
  doc.text(`Student ID: ${student.studentId}`, 14, 77);
  doc.text(`Class: ${student.class}`, 14, 82);

  // Payment Table
  const balance = student.feeAmount - student.paidAmount;
  const tableData = [
    ['Total Fee Amount', `$${student.feeAmount.toFixed(2)}`],
    ['Amount Paid', `$${student.paidAmount.toFixed(2)}`],
    ['Balance Due', `$${balance.toFixed(2)}`],
    ['Status', student.feeStatus]
  ];

  autoTable(doc, {
    startY: 95,
    head: [['Description', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [100, 100, 100] },
    columnStyles: {
      1: { halign: 'right' }
    }
  });

  // Footer
  const finalY = (doc as any).lastAutoTable.finalY + 20;
  doc.setFontSize(10);
  doc.text('Authorized Signature', pageWidth - 60, finalY);
  doc.line(pageWidth - 65, finalY - 5, pageWidth - 15, finalY - 5);

  doc.setTextColor(150, 150, 150);
  doc.text('Generated by EduAssist', pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });

  doc.save(`${student.name}_Fee_Receipt.pdf`);
};
